version: '3.8'

services:
  app:
    build: .
    container_name: laravel_api
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:QDcKnjkaTQYcNqBtdcI/zP5VJlQZwMQHHONqGYNWFnU=
      - DB_CONNECTION=mysql    
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=translation_api_database
      - DB_USERNAME=luffy
      - DB_PASSWORD=root
    depends_on:
      - db
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=translation_api_database
      - MYSQL_USER=luffy
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
